### PR TITLE
Customize how method parameters are serialized

### PR DESCRIPTION
**Pull request by cornerman**
Add annotations for defining how method parameter in an API trait are serialized:

When calling an API method in the client, we need to serialize the parameters of this method, send it to the backend, deserialize it in the backend and then finally call the API method implementation. Each parameter itself can be serialized as defined by your implicit Serializers and Deserializers, but multiple parameters need to be combined into a single, serializable type to be send in a request. You can configure, how *method parameters* are serialized with the following options:
- `@SerializeParametersAs.CaseClass`: Automatically generate a case class representing the parameter lists of each API method: `case class _sloth_Api_fun(a: Int, b: String, c: Double)`. When sending a request, this case class will be used to hold the method parameters, is then serialized and sent to the backend. The backend deserializes the request to this case class and calls the API method implementation. This is the default behaviour.
- `@SerializeParametersAs.Tuple`: Instead of generating a dedicated case class, we just use the `Tuple` type in scala. So instead of the case class, we will serialize and deserialize a tuple: `(Int, String, Double)`.
- `@SerializeParametersAs.Single`: This serialization method expects every API method to only have one parameter. It will then use this single parameter type as the data transfer object. This is the same behaviour as `Tuple` with one argument, but does not compile for more than one argument.

Example:
```scala
@SerializeParametersAs.CaseClass // or: @SerializeParametersAs.Tuple, @SerializeParametersAs.Single
trait Api {
    def fun(a: Int, b: String)(c: Double): F[Int]
}
``` 

see: https://github.com/cornerman/sloth/issues/10

### CODE REVIEW

**Comment by nafg** [comment]
Thanks! I can finally avoid full-auto.

The only thing is, I would rather avoid annotations. Is it possible to "configure" it some other way, perhaps have a different macro invocation? I'd rather have the api itself be fully "ignorant" of the ways it's used (such as Sloth).

**Comment by cornerman** [comment]
> The only thing is, I would rather avoid annotations. Is it possible to "configure" it some other way, perhaps have a different macro invocation?

I see, that would be possible as well and would even give more flexibility. One reason why I chose annotations was that I did not want to add another option that can diverge between client and server (the annotation applies this setting to all usages of this API). If you can do `Client.withTuples(...)` and `Router.withTuples`, you might configure `Client` and `Router` differently by mistake. This is the same as configuring a different `PickleType` for `Client` and `Router`.

An example would be:
```
val client  = Client.serializeParametersAsTuple[Json, F]
val router  = Client.serializeParametersAsCaseClass[ByteBuffer, F]
// These two would not work together.
```

We could accept, that you can do these mistakes, they will lead to a runtime errors, when you launch your app. As a helper, we can introduce some kind of `ServerClientContract` to glue together some configuration for client and server. This could hold the `PickleType` and the `SerializeParametersAs` configuration. So you could define your server/client like this:

```scala
val jsonConfig = ServerClientContract.serializeParametersAsTuple[Json]

val client = jsonConfig.Client.wire[F]
val router = jsonConfig.Router[F].route[Api](ApiImpl)
```

What do you think?

**Comment by cornerman** [comment]
As a sidenote: I will probably make `Tuple` serialization the default. It compiles faster and has less requirements on the used serialization api regarding auto-derivation.

**Comment by nafg** [comment]
If tuples will be the default I don't care if it's changed via an annotation because I will probably go with the default.

As for ensuring the client and server are generated the same, for that reason and others I've been doing the following. I define this in a cross-compiled module:

```scala
trait ApiModule {
  type ApiResult[T] = Kleisli[Future, Option[ActingUser], T]

  type Api[F[_]]

  type ServerApi = Api[ApiResult]
  type ClientApi = Api[Future]

  protected implicit def circeSerializer[T: Encoder]: Serializer[T, String] = _.asJson.noSpaces
  protected implicit def circeDeserializer[T: Decoder]: Deserializer[T, String] =
    parser.decodeAccumulating[T](_).toEither.left.map(Errors)

  protected implicit def monadError(implicit executionContext: ExecutionContext): MonadError[Future, Throwable] =
    cats.instances.future.catsStdInstancesForFuture

  protected def route(implicit c: ExecutionContext): (Router[String, ApiResult], ServerApi) => Router[String, ApiResult]
  protected def wire: Client[String, Future, ClientException] => ClientApi

  val prefix = getClass.getName

  def routeAlone(apiImpl: ServerApi)(implicit executionContext: ExecutionContext): Router[String, ApiResult] =
    route.apply(Router[String, ApiResult], apiImpl)

  def wirePrefixed(f: String => Client[String, Future, ClientException]) = wire(f(prefix))
}
```

Then specific apis extend ApiModule and define an Api trait inside, also implementing the two methods that actually call the macros:

```scala
object DoctorContactsApiModule extends ApiModule {
  trait Api[F[_]]
    extends CRUDApi[F, LLookup[DoctorContact], DoctorContact, LKEnt[DoctorContact]]
      with NotesApi[F, DoctorContact] {
    def forDoctor(doctor: LLookup[Doctor]): F[Seq[LKEnt[DoctorContact]]]
  }
  override protected def route(implicit executionContext: ExecutionContext) = _.route(_)
  override protected def wire = _.wire[ClientApi]
}
```

(CRUDApi and NotesApi define some methods that several APIs share.)

This file only has to import `io.circe.generic.auto._` (and orphan encoder and decoder instances for things it can't auto-derive).

Essentially, I've decoupled "run the macro on the set of methods in this trait" from any server-specific or client-specific code.

The downside to this is that the macro logic runs four times -- it has to generate the router and the client from the trait, in a module that's compiled for both JVM and JS.

Previously, incremental compilation wasn't smart enough to run the macro whenever the API trait changed. This way they are always in the same file. Also, since I'm calling the macro for each API in its own file, I don't trigger rerunning the macro for an API that wasn't changed just because it's in a file that was invalidated.

**Comment by ddw-tsc** [comment]
I'm glad to see progress on #10 here! But I do have a reservation about the current proposal. To me, needing an annotation defining the transport type accompanying the trait definition is a serious case of leaking implementation details into the interface. The API interface shouldn't be tied to it's transport - in theory, you could have the same interface over different transports, e.g. a binary interface over websockets with a fallback to JSON over HTTP.

Would it not be possible, instead of annotations on the trait, to have different client (and server) macros like `CaseClassClient`, `TupleClient`, `SingleArgumentClient` ? It's a choice the user has to make at the time of implementing the transport along with the `PickleType`, etc.

**Comment by cornerman** [comment]
@ddw-tsc Thank you for your Input :)

Actually, I totally agree with you, the annotations leak information and force a certain style all users of this API. This is mainly the reason I have not merged this PR yet. I would like to define this configuration outside of annotations but this was the first version that I could implement quite easily.

There is just one problem with moving it out of the `Api`-trait: We need to do the same on the server and the client (either both use case-class or both use tuple or both use single argument). They would not work together if configured differently. For this, I think we should have some kind of Client-Server-Contract that you can use to configure both - so you get consistent behaviour and define it once. Ideas are very welcome :)

**Comment by nafg** [comment]
In fact the issue of guaranteeing a shared serialization format exists already, since you can have different imports in the file that wires the server and that wires the client.

Above I posted my solution to this. It consists of decoupling "using the wiring macro that generates the code" from the actual server or client implementation. This way I run both macros alongside the trait. This has the downside that when the trait needs to be cross-compiled (e.g. JVM and JS) both macros need to run twice. If there was one macro that did both code generatings it might be a bit faster but ultimately it will be slower, especially if you use full-auto codec derivation e.g. from circe-generic. However it guarantees that the macro for both client and server are run with the same imports in scope. (Having one macro would make the guarantee even stronger since you could technically have an import in a local scope, but that would be very unlikely to happen unintentionally.)

(In my implementation I structure this by putting my API traits inside their own module which extends a base trait that facilitates this setup, however that is just to make it more convenient.)

Of course this doesn't guarantee that your Encoder and Decoder for a given type are symmetric; that is a general issue...

**Comment by ddw-tsc** [comment]
IMO, as nafg has demonstrated above, once you have the general building blocks, you can easily define extra constraints to ensure types match up. As a high-level concept, couldn't one do something like the following?
```
trait TupleRPC[A] ... {
  val client: TupleClient[A] = ...
  val server: TupleServer[A] = ...
  ...
}
```

Then , if I have `object myRPC extends TupleRPC[MyApiTrait]...`, calls to `myRPC.client` and `myRPC.server` will use the same strategy. And you can add more parameters for the serialized type, etc. to the `TupleRPC` trait to make sure more things line up. But I'd still recommend this being an additional building block on top of the raw client & server macros, because sometimes not all server types are simple to express on the client side, so one should have the option of falling back to raw wiring as it was in autowire.

**Comment by cornerman** [comment]
@nafg @ddw-tsc What you are proposing makes sense to me! I also think, it would be good to keep the raw building blocks and invent a structure and API around it to get convenient helpers for the server-client contract.

Currently, I am just really short on time and will not be able to pick this up right now. If anyone is interested, a PR or some help would be awesome :)

**Comment by nafg** [comment]
I've factored out my ApiModule and related code to GitHub (https://github.com/nafg/sloth-apimodule) and published to bintray jcenter (io.github.nafg.sloth-api-module:core:0.1.0)

**Comment by cornerman** [comment]
Will switch to tuple generation as only method of serialization. There for closing this one. See #100 

In the end, I think the configuration is not really beneficial. Tuple serialization works out of the box with most libraries. And if you really want a nice json serialization with pretty names, then you can just use any case class as your single method parameter.

**Pull request closed without merging**
